# -*- coding: utf-8 -*-
"""IDS / SOC system

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/zaraabdulameer/ids-soc-system.b789f138-17e6-4e07-9397-8c7175258273.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260104/auto/storage/goog4_request%26X-Goog-Date%3D20260104T173344Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D4ba0065d53f255b068d7fe39189c5874201448e193b96bf367f1c0baa6de63de32ed93637c6d191ebb1e1c73b355546cdad0460f094bb489c73dfc8ac9bcedf14c7d52b26c79060f88382789cdc2e174e570b17c37164b622f200b03dc9a1c9b70a705e11eeb6c78000bacc5a8f19f8ed59231e0b21b445b914316f61348ac1ac47901efeae9cadee1ce21d2dff3f13e86d8e00e5c4473d13c093f53d7fdb6f335c167b08ca276c5fb3863f1ca98b259ef288aa32d3b8905b35e00659a77bda0eedb7c6a719f515fa0185096946970c4b5f00864ab94d41424108084c07a065dc86afee07be7a1ff71e2230b62aabc170a9e408036c2e9374439a43bc8c04697
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
mrwellsdavid_unsw_nb15_path = kagglehub.dataset_download('mrwellsdavid/unsw-nb15')

print('Data source import complete.')

import pandas as pd
dftest=pd.read_csv('/kaggle/input/unsw-nb15/UNSW_NB15_testing-set.csv')
dftrain=pd.read_csv('/kaggle/input/unsw-nb15/UNSW_NB15_training-set.csv')
print(f'shape',dftest.shape)
print(f'shape2',dftrain.shape)

dftrain.head()

dftrain['attack_cat'].value_counts()

dftrain=dftrain.drop(['id'],axis=1)
dftest=dftest.drop(['id'],axis=1)

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
dftrain['attack_cat'] = le.fit_transform(dftrain['attack_cat'])
dftest['attack_cat'] = le.fit_transform(dftest['attack_cat'])

dftrain.head()

cols_to_drop = ['proto', 'service', 'state']

dftrain = dftrain.drop(columns=cols_to_drop)
dftest  = dftest.drop(columns=cols_to_drop)

import numpy as np

# Replace infinities with NaN first
dftrain.replace([np.inf, -np.inf], np.nan, inplace=True)

# Count again after replacement
nan_counts_after_inf = dftrain.isna().sum()
print(nan_counts_after_inf[nan_counts_after_inf > 0])

from imblearn.ensemble import BalancedRandomForestClassifier
from sklearn.metrics import classification_report

feature_cols = [c for c in dftrain.columns if c not in ['attack_cat','label']]


X_full = dftrain[feature_cols]
y_full = dftrain['attack_cat']

# Initialize the classifier
brf = BalancedRandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)
brf.fit(X_full, y_full)

# Features and labels for test set
X_test = dftest[feature_cols]
y_test = dftest['attack_cat']

# Predict on test set
y_pred = brf.predict(X_test)

# Classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

comparison_df = pd.DataFrame({
    "Actual": y_test,
    "Predicted": y_pred
})

# Show first 10 rows
print(comparison_df.head(5))
multi_classdf=comparison_df.to_csv("prediction_vs_actual.csv", index=False)

from imblearn.ensemble import BalancedRandomForestClassifier
from sklearn.metrics import classification_report
import pandas as pd

# Feature columns (drop both targets)
feature_cols = [c for c in dftrain.columns if c not in ['attack_cat', 'label']]

# Training data
X_train = dftrain[feature_cols]
y_train = dftrain['label']   # binary target

# Test data
X_test = dftest[feature_cols]
y_test = dftest['label']

# Model
brf_label = BalancedRandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

# Train
brf_label.fit(X_train, y_train)

# Predict
y_pred = brf_label.predict(X_test)

# Evaluation
print(classification_report(y_test, y_pred))

# Prediction vs Actual
binary_df = pd.DataFrame({
    "Actual": y_test,
    "Predicted": y_pred
})

print(binary_df.head(10))

print(X_train.columns.tolist())

# ---------------- Multi-class predictions ----------------
X_test_multi = dftest[feature_cols]
y_test_multi = dftest['attack_cat']  # multi-class target
y_pred_multi = brf.predict(X_test_multi)

multi_classdf = pd.DataFrame({
    "Actual_Label": y_test_multi,
    "Predicted_Label": y_pred_multi
})

# ---------------- Binary predictions ----------------
X_test_bin = dftest[feature_cols]
y_test_bin = dftest['label']  # binary target
y_pred_bin = brf_label.predict(X_test_bin)

binary_df = pd.DataFrame({
    "Actual_Label": y_test_bin,
    "Predicted_Label": y_pred_bin
})

# Multi-class confidence
multi_class_conf = brf.predict_proba(X_test)  # shape: (n_samples, n_classes)
multi_classdf['Confidence'] = multi_class_conf.max(axis=1)  # max probability per row

# Binary confidence (probability of being attack = 1)
binary_conf = brf_label.predict_proba(X_test)[:,1]
binary_df['Confidence'] = binary_conf

def severity_label(conf):
    if conf >= 0.85:
        return "High"
    elif conf >= 0.6:
        return "Medium"
    else:
        return "Low"

multi_classdf['Severity'] = multi_classdf['Confidence'].apply(severity_label)
binary_df['Severity'] = binary_df['Confidence'].apply(severity_label)

multi_classdf.to_csv("multi_classdf_with_confidence.csv", index=False)
binary_df.to_csv("binary_df_with_confidence.csv", index=False)

# --- Binary threshold ---
binary_threshold = 0.6
binary_df['Binary_Predicted'] = (binary_df['Confidence'] >= binary_threshold).astype(int)

# --- RAG ---
def assign_rag(conf):
    if conf >= 0.85:
        return "Red"
    elif conf >= 0.6:
        return "Amber"
    else:
        return "Green"

binary_df['RAG'] = binary_df['Confidence'].apply(assign_rag)

binary_df['Attack_Type'] = 0  # default 0 for no attack
mask_attack = binary_df['Binary_Predicted'] == 1
binary_df.loc[mask_attack, 'Attack_Type'] = multi_classdf.loc[mask_attack, 'Predicted_Label']

# MultiClass Confidence: only for predicted attacks, else 0
binary_df['MultiClass_Confidence'] = 0.0
binary_df.loc[mask_attack, 'MultiClass_Confidence'] = multi_classdf.loc[mask_attack, 'Confidence']

soc_df = binary_df[['Actual_Label', 'Binary_Predicted', 'Attack_Type',
                    'Confidence', 'MultiClass_Confidence', 'RAG', 'Severity']]
soc_df.head(20)

# --- Function to assign Severity based on RAG ---
def assign_severity(rag, attack_type=None):
    """
    Assigns severity level based on RAG.
    - Red -> High
    - Amber -> Medium
    - Green -> Low
    """
    if rag == 'Red':
        return 'High'
    elif rag == 'Amber':
        return 'Medium'
    else:
        return 'Low'
binary_df['Severity'] = binary_df['RAG'].apply(assign_severity)

# Function to convert alerts DataFrame to text , for deployment nec
def alerts_to_text(df, max_rows=20):
    """
    Converts top alerts in a DataFrame to a readable text format.
    df: alerts DataFrame (binary or multi-class)
    max_rows: maximum number of rows to include
    """
    rows = df.head(max_rows).to_dict(orient="records")
    text = ""
    for r in rows:
        text += f"""
Attack_Type: {r.get('Predicted_Label', r.get('Attack_Type', 'N/A'))}
Confidence: {round(r.get('Confidence', 0), 2)}
RAG: {r.get('RAG', 'N/A')}
Severity: {r.get('Severity', 'N/A')}
---
"""
    return text


# ================================
# Filter high severity alerts
# ================================

high_binary = binary_df[binary_df['Severity'] == 'High']
high_multi = multi_classdf[multi_classdf['Severity'] == 'High']


# ================================
# Convert alerts to text
# ================================

binary_text = alerts_to_text(high_binary)
multi_text = alerts_to_text(high_multi)


# Compose SOC prompt
soc_prompt = f"""
You are a SOC Level-2 cybersecurity analyst.

Analyze the following intrusion detection alerts.

Tasks:
1. Summarize the security situation
2. Identify the most dangerous threats
3. Suggest response actions for the SOC team
4. Highlight patterns or repeated attacks

=== BINARY ALERTS ===
{binary_text}

=== MULTICLASS ALERTS ===
{multi_text}
"""

def build_soc_prompt(row):
    return f"""
You are a SOC analyst assistant.

Alert details:
- Prediction: {row.get('Predicted_Label', 'N/A')}
- Confidence Score: {row.get('Confidence', 0):.2f}
- Severity: {row.get('Severity', 'N/A')}
- RAG Status: {row.get('RAG', 'N/A')}

Explain:
1. What this alert means
2. Why it is risky
3. What action the SOC analyst should take

Keep the explanation concise and professional.
"""

# for deployment reason full pipeline
Binary model predictions
binary_conf = brf_label.predict_proba(X_test)[:, 1]
binary_pred = (binary_conf >= 0.45).astype(int)  ## SOC threshold: classify as attack if probability >= 0.45
                                                  # Slightly lower than 0.5 to increase detection (higher recall)
                                                   # Adjust if too many false positives overwhelm analysts
# Multi-class model predictions
multi_class_pred = brf.predict(X_test)
multi_class_conf = brf.predict_proba(X_test).max(axis=1)

# Binary DataFrame
binary_df = pd.DataFrame({
    'Actual_Label': y_test,
    'Binary_Predicted': binary_pred,
    'Confidence': binary_conf
})

# Multi-class DataFrame
multi_classdf = pd.DataFrame({
    'Predicted_Label': multi_class_pred,
    'Confidence': multi_class_conf
})

# Assign RAG
def assign_rag(conf):
    if conf >= 0.85:
        return 'Red'
    elif conf >= 0.6:
        return 'Amber'
    else:
        return 'Green'

binary_df['RAG'] = binary_df['Confidence'].apply(assign_rag)
multi_classdf['RAG'] = multi_classdf['Confidence'].apply(assign_rag)

# Assign Severity
def assign_severity(rag):
    if rag == 'Red':
        return 'High'
    elif rag == 'Amber':
        return 'Medium'
    else:
        return 'Low'

binary_df['Severity'] = binary_df['RAG'].apply(assign_severity)
multi_classdf['Severity'] = multi_classdf['RAG'].apply(assign_severity)

# Build final SOC DataFrame
final_soc_df = binary_df.copy()

# ONLY assign multi-class values if binary predicts attack (1)
final_soc_df['Attack_Type'] = [
    multi_classdf.loc[i, 'Predicted_Label'] if binary_pred[i] == 1 else 0
    for i in range(len(binary_df))
]

final_soc_df['MultiClass_Confidence'] = [
    multi_classdf.loc[i, 'Confidence'] if binary_pred[i] == 1 else 0
    for i in range(len(binary_df))
]

# SOC Playbook
def assign_playbook(severity):
    if severity == 'High':
        return "Immediate response required: Isolate affected host, block suspicious IPs, escalate to Tier-2 SOC analyst."
    elif severity == 'Medium':
        return "Investigate alert: review logs, monitor traffic, no immediate containment."
    else:
        return "Log event and continue monitoring."

final_soc_df['SOC_Playbook'] = final_soc_df['Severity'].apply(assign_playbook)

# Columns for SOC
final_soc_df = final_soc_df[
    ['Actual_Label', 'Binary_Predicted', 'Attack_Type',
     'Confidence', 'MultiClass_Confidence', 'RAG', 'Severity', 'SOC_Playbook']
]

final_soc_df.to_csv("SOC_final_alerts_corrected.csv", index=False)
final_soc_df.head(20)

from sklearn.metrics import confusion_matrix, classification_report

# Load your final SOC CSV
df = pd.read_csv("SOC_final_alerts_corrected.csv")

# Extract actual and predicted labels
y_true = df['Actual_Label']
y_pred = df['Binary_Predicted']

# Confusion Matrix
cm = confusion_matrix(y_true, y_pred)
print("Confusion Matrix:\n", cm)

# Classification Report
report = classification_report(y_true, y_pred)
print("\nClassification Report:\n", report)

# Optional accuracy check
accuracy = (y_true == y_pred).mean()
print(f"\nAccuracy: {accuracy:.4f}")

"""_________________________________________________________________________________________________________________

________________ ___________________
"""

import gradio as gr
import numpy as np
def predict_soc(*inputs):
    # Build input dataframe
    input_df = pd.DataFrame([inputs], columns=feature_cols)

    # ========== Binary Model ==========
    binary_probs = brf_label.predict_proba(input_df)[0]
    binary_conf = float(binary_probs[1])
    is_attack = binary_conf >= 0.25

    # ========== NORMAL TRAFFIC ==========
    if not is_attack:
        return {
            "Traffic_Type": "Normal",
            "Binary_Confidence": round(binary_conf, 3),
            "Attack_Type": "Normal",
            "MultiClass_Confidence": 0.0,
            "RAG": "Green",
            "Severity": "Low",
            "SOC_Playbook": "Log event and continue monitoring."
        }

    # ========== MULTI-CLASS MODEL ==========
    multi_probs = brf.predict_proba(input_df)[0]
    max_idx = int(np.argmax(multi_probs))
    attack_type = brf.classes_[max_idx]
    multi_conf = float(multi_probs[max_idx])

    # ========== RAG & SEVERITY ==========
    if binary_conf >= 0.6:
        rag = "Red"
        severity = "High"
        playbook = (
            "Immediate response required: isolate affected host, "
            "block malicious IPs, escalate to Tier-2 SOC analyst."
        )
    elif binary_conf >= 0.25:
        rag = "Amber"
        severity = "Medium"
        playbook = (
            "Investigate alert: review logs, monitor traffic, "
            "no immediate containment required."
        )
    else:
        rag = "Green"
        severity = "Low"
        playbook = "Log event and continue monitoring."

    return {
        "Traffic_Type": "Attack",
        "Binary_Confidence": round(binary_conf, 3),
        "Attack_Type": attack_type,
        "MultiClass_Confidence": round(multi_conf, 3),
        "RAG": rag,
        "Severity": severity,
        "SOC_Playbook": playbook
    }

inputs = [
    gr.Number(label=col, value=0.0)
    for col in feature_cols
]

outputs = gr.JSON(label="SOC Alert Output")

app = gr.Interface(
    fn=predict_soc,
    inputs=inputs,
    outputs=outputs,
    title="SOC Intrusion Detection System (ML-Based)",
    description=(
        "Enter numeric network flow features. "
        "The system performs real-time intrusion detection "
        "using binary + multi-class ML models."
    )
)

app.launch()

import joblib

# Save already-trained models
joblib.dump(brf_label, "brf_label.pkl")
joblib.dump(brf, "brf.pkl")

print("Models saved successfully")

dftrain.columns